name: Detect changes

on:
  push:
    #paths:
    #  - 'apps/**'
    branches:
      - main

jobs:
  detect-changes:
    name: Format with prettier
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.changed-files.outputs.result }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - run: git diff --name-only HEAD^ HEAD apps > changes.txt

      - uses: actions/github-script@v6
        id: changed-files
        with:
          result-encoding: string
          script: |
            const fs = require('fs');

            const allFileContents = fs.readFileSync('changes.txt', 'utf-8');
            const generator = allFileContents
            .split(/\r?\n/)
            .slice(0, -1)
            .map(line => line.split('/')[1])
            .filter((v, i, a) => a.indexOf(v) === i)

            return JSON.stringify({ generator })

      - name: Get result
        run: echo "${{steps.changed-files.outputs.result}}"

  build:
    needs: [detect-changes]
    name: Build application
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}

    steps:
      - run: echo ${{ matrix.generator }}
