name: Cut a Release

on:
  repository_dispatch:
    types: [cut-release]

jobs:
  dispatch:
    name: Test event
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          packages=${{ join(github.event.inputs.packages || github.event.client_payload.packages, ' ') }}
          echo $packages

          for PKG in ${packages[@]}; do
            echo $PKG
          done
