name: Cut a Release

on:
  repository_dispatch:
    types: [cut-release]
  workflow_dispatch:
    inputs:
      packages:
        description: 'Emergencies only. Release a package from `main`. Enter the folder name under packages/. e.g. wsj'
        required: true

jobs:
  dispatch:
    name: Test event
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          packages=(${{ join(github.event.inputs.packages || github.event.client_payload.packages, ' ') }})
          echo $packages

          for PKG in ${packages[@]}; do
            echo $PKG
          done
  github_release:
    runs-on: ubuntu-latest
    needs: [dispatch]

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(github.event.inputs.packages) || github.event.client_payload.packages }}
    steps:
      - run: echo ${{ matrix.package }}
